apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-dns
spec:
  externalIPs:
  - 10.28.1.70
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: nginx-dns
